graph TB
    subgraph NODE["Node"]
        subgraph SYNC["Syncing"]
            subgraph DB["Database"]
                CONTENT["Content"]
                BLOCKCHAIN["Blockchain"]
                subgraph IDX["Indexing"]
                    CURRENT["Current"]
                    INDEXES["Indexes"]
                end
            end
            subgraph CONNECTIONS["Connections"]
                subgraph USERS["User"]
                    USRMETA["Meta Date"]
                    USRPRV["Private Key"]
                    USRPUB["Public Key"]
                    USRSHRD["Shared Key"]
                end
            end
        end
        subgraph DISC["Discovery"]
            KNOWN["Known Peers"]
        end
        subgraph UM["User Management"]
            NUSER["Node User"]
            META["Meta Data"]
        end
    end
